--------------------------------------------------------
--  Fichier créé - jeudi-avril-06-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LONGUEURPISTESVELO
--------------------------------------------------------

  CREATE TABLE "EDM115"."LONGUEURPISTESVELO" 
   (	"CODE_QUARTIER" NUMBER, 
	"AMENAGEMENT_CYCLABLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into EDM115.LONGUEURPISTESVELO
SET DEFINE OFF;
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('1','21548,7');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('2','22597,3');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('3','4403,09');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('4','30522,9');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('5','28078,6');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('6','32398,2');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('7','16718,2');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('8','22945,8');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('9','31816,2');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('10','48780,2');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('11','15508,3');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('14301','7854,51939');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('14302','4808,84936');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('14303','6371,53907');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('14304','7628,89349');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('14305','9288,95165');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('14306','4688,33283');
Insert into EDM115.LONGUEURPISTESVELO (CODE_QUARTIER,AMENAGEMENT_CYCLABLE) values ('14307','13172,9418');
--------------------------------------------------------
--  DDL for Index PK_LONGUEURPISTESVELO
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDM115"."PK_LONGUEURPISTESVELO" ON "EDM115"."LONGUEURPISTESVELO" ("CODE_QUARTIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_AMENAGEMENT_CYCLABLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDM115"."UQ_AMENAGEMENT_CYCLABLE" ON "EDM115"."LONGUEURPISTESVELO" ("AMENAGEMENT_CYCLABLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LONGUEURPISTESVELO
--------------------------------------------------------

  ALTER TABLE "EDM115"."LONGUEURPISTESVELO" ADD CONSTRAINT "UQ_AMENAGEMENT_CYCLABLE" UNIQUE ("AMENAGEMENT_CYCLABLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EDM115"."LONGUEURPISTESVELO" ADD CONSTRAINT "PK_LONGUEURPISTESVELO" PRIMARY KEY ("CODE_QUARTIER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EDM115"."LONGUEURPISTESVELO" MODIFY ("AMENAGEMENT_CYCLABLE" CONSTRAINT "NN_AMENAGEMENT_CYCLABLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LONGUEURPISTESVELO
--------------------------------------------------------

  ALTER TABLE "EDM115"."LONGUEURPISTESVELO" ADD CONSTRAINT "FK_LONGUEURPISTESVELO_QN" FOREIGN KEY ("CODE_QUARTIER")
	  REFERENCES "EDM115"."QUARTIERSNANTES" ("IDENTIFIANT") ENABLE;
