--------------------------------------------------------
--  Fichier créé - jeudi-avril-06-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUARTIERSNANTES
--------------------------------------------------------

  CREATE TABLE "EDM115"."QUARTIERSNANTES" 
   (	"IDENTIFIANT" NUMBER, 
	"QUARTIER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into EDM115.QUARTIERSNANTES
SET DEFINE OFF;
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('1','Centre Ville');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('2','Bellevue - Chantenay - Sainte Anne');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('3','Dervallières - Zola');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('4','Hauts Pavés - Saint Félix');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('5','Malakoff - Saint-Donatien');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('6','Ile de Nantes');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('7','Breil - Barberie');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('8','Nantes Nord');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('9','Nantes Erdre');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('10','Doulon - Bottière');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('11','Nantes Sud');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('14301','Trentemoult');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('14302','Hôtel de Ville');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('14303','Château de Rezé');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('14304','Pont Rousseau');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('14305','La Houssais');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('14306','Blordière');
Insert into EDM115.QUARTIERSNANTES (IDENTIFIANT,QUARTIER) values ('14307','Ragon');
--------------------------------------------------------
--  DDL for Index PK_QUARTIERSNANTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDM115"."PK_QUARTIERSNANTES" ON "EDM115"."QUARTIERSNANTES" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_QUARTIER
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDM115"."UQ_QUARTIER" ON "EDM115"."QUARTIERSNANTES" ("QUARTIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QUARTIERSNANTES
--------------------------------------------------------

  ALTER TABLE "EDM115"."QUARTIERSNANTES" ADD CONSTRAINT "UQ_QUARTIER" UNIQUE ("QUARTIER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EDM115"."QUARTIERSNANTES" ADD CONSTRAINT "PK_QUARTIERSNANTES" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EDM115"."QUARTIERSNANTES" MODIFY ("QUARTIER" CONSTRAINT "NN_QUARTIER" NOT NULL ENABLE);
